<?php 
/**
 * @version		2.2
 * @Project		Facebook Like Box
 * @author 		Sunento Wu	
 * @package		
 * @copyright	Copyright (C) 2010 Vivociti.com. All rights reserved.
 * @license 	http://www.gnu.org/licenses/old-licenses/gpl-2.0.html GNU/GPL version 2
 * URL : http://vivociti.com
* Description : Facebook Like Box is a social module that enables Facebook Page owners to attract and gain Likes from their own website. The Like Box enables users to: see how many users already like this page, and which of their friends like it too, read recent posts from the page and Like the page with one click, without needing to visit the page
* Generated By : YouCMSAndBlog IDE Joomla Module Plugin (http://vivociti.com)
* (please support YouCMSAndBlog by promoting it, dont remove above line. Thanks.)
* WE LOVE JOOMLA! 
*/
/// no direct access 
defined('_JEXEC') or die('Restricted access'); 
//Get parameters 
//The ID of the Facebook Page for this Like Box
$pageID = $params->get('pageID', ''); //123961057630124
//The Page URL of the Facebook Page for this Like Box
$pageURL = $params->get('pageURL', '');  ////example of Page URL : http://www.facebook.com/pages/VivoCiticom-Joomla-Wordpress-Blogger-Drupal-DNN-Community/119691288064264
//The Width of the module in pixes
$width = $params->get('width'); 
$height = $params->get('height'); 

$layoutMode = $params->get('layoutMode'); 

//Selected Color Scheme
$colorScheme = $params->get('colorScheme');
//Show a sample of this many users who have liked this Page
$connection = $params->get('connection'); 
//Show the profile stream for Public Profile
$streams = $params->get('streams'); 
//Show the profile photo
$showFaces = $params->get('showFaces'); 
//Show the Find Us on Facebook bar at top. Only shown when either stream or connections are present
$header = $params->get('header'); 
//Show Author Credit, this is free module
$moduleBy = $params->get('moduleBy'); 

if ($showFaces == "yes") {
	$showFaces == "true";	
} else {
	$showFaces == "false";
}
if ($streams == "yes") {
	$streams == "true";
	$height = $height + 300;
} else {
	$streams == "false";
}
if ($header == "yes") {
	$header == "true";
	$height = $height + 32;
} else {
	$header == "false";
}

$html = ""; 
$img_live_dir = 'http://vivociti.com/images/plus2x2.gif';
$html = "<a href=\"http://vivociti.com/content/category/7/44/53/\" title=\"Free Facebook Like Box for Joomla is authored by VivoCiti.com\" target=\"_blank\"><img src=\"$img_live_dir\" border=\"0\"/></a>"; 

	//this is to check for backward compatibility, previous version all is using Page ID instead of Page URL
		//If Page URL is filled, we will use it
	$isUsingPageURL = false;
	
	echo $height;
	if (strlen($pageURL) > 23) {	
				$isUsingPageURL = true;  //flag to be used for backward
				$like_box_iframe = "<iframe src=\"http://www.facebook.com/plugins/likebox.php?href=$pageURL&amp;width=$width&amp;colorscheme=$colorScheme&amp;show_faces=$showFaces&amp;connections=$connection&amp;stream=$streams&amp;header=$header&amp;height=$height\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:" . $width . "px; height:" . $height . "px;\" allowTransparency=\"true\"></iframe>";
				$like_box_xfbml = "<script src=\"http://connect.facebook.net/pt_BR/all.js#xfbml=1\"></script><fb:like-box href=\"$pageURL\" width=\"$width\" show_faces=\"$showFaces\" stream=\"$streams\" header=\"$header\"></fb:like-box>";
	} else {
		$like_box_iframe = "<iframe src=\"http://www.facebook.com/plugins/likebox.php?id=$pageID&amp;width=$width&amp;colorscheme=$colorScheme&amp;show_faces=$showFaces&amp;connections=$connection&amp;stream=$streams&amp;header=$header&amp;height=$height\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:" . $width . "px; height:" . $height . "px;\" allowTransparency=\"true\"></iframe>";
		$like_box_xfbml = "<script src=\"http://connect.facebook.net/en_US/all.js#xfbml=1\"></script><fb:like-box id=\"$pageID\" width=\"$width\" show_faces=\"$showFaces\" stream=\"$streams\" header=\"$header\"></fb:like-box>";		
	}
	
	if (strcmp($layoutMode, "iframe") == 0) {
		echo $like_box_iframe;
	} else {
		echo $like_box_xfbml;
	}
	if ($moduleBy == "no") {
		echo $html;
	}
?>


